/* Euterpe service worker — generated by build.js from src/sw.template.js
   (1.27.1 is filled in so each release gets a fresh cache). Offline-first:
   precache the single-file app + icons, serve the cached shell for navigations,
   runtime-cache Google Fonts. All URLs are RELATIVE so it works whether the app
   is served from a domain root or a GitHub Pages subpath (/guitar-studio/). */
'use strict';
const CACHE = 'euterpe-1.27.1';
const CORE = [
  './',
  './index.html',
  './manifest.webmanifest',
  './icons/icon.svg',
  './icons/icon-192.png',
  './icons/icon-512.png',
  './icons/icon-maskable.png',
  './icons/apple-touch-icon.png',
];

self.addEventListener('install', (e) => {
  // Precache the shell, then WAIT (no auto-skipWaiting): on an update an existing
  // tab keeps the old worker in control while the new one parks in 'waiting', so
  // the page can offer a reload (14-pwa.js) instead of swapping out mid-session.
  // On a first install there's no controller to wait behind, so it activates at once.
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(CORE)));
});

// The page posts this when the user accepts the update toast — take over now,
// which fires 'controllerchange' in the page and triggers a single reload.
self.addEventListener('message', (e) => {
  if (e.data && e.data.type === 'SKIP_WAITING') self.skipWaiting();
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE && k.startsWith('euterpe-')).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);

  // Navigations always get the cached app shell (the whole app is one file).
  if (req.mode === 'navigate') {
    e.respondWith(caches.match('./index.html').then((r) => r || fetch(req)));
    return;
  }

  // Same-origin: cache-first, then network (and cache what we fetch).
  if (url.origin === self.location.origin) {
    e.respondWith(
      caches.match(req).then((r) => r || fetch(req).then((resp) => {
        const copy = resp.clone();
        caches.open(CACHE).then((c) => c.put(req, copy));
        return resp;
      }).catch(() => caches.match('./index.html')))
    );
    return;
  }

  // Cross-origin (Google Fonts): stale-while-revalidate.
  e.respondWith(
    caches.match(req).then((cached) => {
      const net = fetch(req).then((resp) => {
        const copy = resp.clone();
        caches.open(CACHE).then((c) => c.put(req, copy));
        return resp;
      }).catch(() => cached);
      return cached || net;
    })
  );
});
